Relative duration query params
temporalio/ui pull request #1409
Opened 2023-06-05 18:38 UTC by Alex-Tideman

## Description & motivation 💭 
It can be really useful to allow a relative time in our query params to set a filter (without using DateTimes). For example, having a link with ?earliestTime=5m would show all workflows within the last 5 minutes, and you could bookmark it to always get the last 5 minutes.

tctl allows for this already with the --earliest_time and --latest_time options. 
https://docs.temporal.io/tctl-v1/workflow#--earliest_time

This PR handles the optional query param ?earliestTime and ?latestTime to convert the relative durations into absolute times to query against. If one of these query params are set, the DateTime filtering UI is disabled and will only use the relative times.

There is no UI to set this query param, you would need to enter it yourself. We could definitely add this to the UI in another PR, but the goal of this param is mostly for links.

Relative time durations accepted:

```
second, seconds, s = seconds
minute, minutes, m = minutes
hour, hours, h = hours
day, days, d = days
week, weeks, w = weeks
month, months, M = months
year, years, y = years

``` 

### Screenshots (if applicable) 📸 
<img width="1656" alt="Screen Shot 2023-06-05 at 1 32 11 PM" src="https://github.com/temporalio/ui/assets/7967403/01d70957-776f-4f53-beca-70505e455468">

<img width="1658" alt="Screen Shot 2023-06-05 at 1 31 59 PM" src="https://github.com/temporalio/ui/assets/7967403/7d5664d8-1aa6-4081-b217-2613ccefaea1">

<img width="1653" alt="Screen Shot 2023-06-05 at 1 34 15 PM" src="https://github.com/temporalio/ui/assets/7967403/ee0f677c-6577-4ce0-acca-f81a05d8ded0">

### Design Considerations 🎨 
Would like feedback on the disabled label 'Latest time 10 weeks'

## Testing 🧪 

### How was this tested 👻 

- [ ] Manual testing
- [ ] E2E tests added
- [ ] Unit tests added

### Steps for others to test: 🚶🏽‍♂️🚶🏽‍♀️ 

## Checklists

### Draft Checklist 

### Merge Checklist 

### Issue(s) closed 

## Docs

### Any docs updates needed?

2023-06-06 04:03 UTC, laurakwhit requested changes

2023-06-06 04:03 UTC, laurakwhit commented on src/lib/stores/workflows.ts
> +      latestRelativeDuration: $latestRelativeDuration,
Do we need these here to update Workflows if the user has to enter a change in the url and hit enter?

2023-06-06 14:51 UTC, Alex-Tideman commented on src/lib/components/workflow/dropdown-filter/workflow-datetime-filter.svelte
> +          timeFilter.value,
How did you set the date/time query? With the search input? 

How I have it working is always use the relative time if it's in the url and ignore other date/time queries and disable the date/time filter. So I can clear out the relative time query if they set a date/time one, just curious how you were able to set it.

2023-06-06 14:53 UTC, Alex-Tideman commented on src/lib/components/workflow/dropdown-filter/workflow-datetime-filter.svelte
> +  $: latestRelativeDuration = $page.url.searchParams.get('latestTime');
Good catch!

2023-06-06 16:43 UTC, laurakwhit commented on src/lib/components/workflow/dropdown-filter/workflow-datetime-filter.svelte
> +          timeFilter.value,
Repro. steps are
* set the date/time query from the filter dropdown
* add on the the url (e.g. `&latestTime=10M`) and hit enter

![Screenshot 2023-06-06 at 10 40 35 AM](https://github.com/temporalio/ui/assets/15069288/20432975-4435-4205-8ca5-626de5db116b)
![Screenshot 2023-06-06 at 10 41 05 AM](https://github.com/temporalio/ui/assets/15069288/5da66515-5fbb-4b51-bf74-04b30ddc70ea)

2023-06-07 18:48 UTC, Alex-Tideman commented on src/lib/components/workflow/dropdown-filter/workflow-datetime-filter.svelte
> +          timeFilter.value,
I don't envision anyone using like this but they absolutely could. I think adding a 'Clear Relative Time' button or something will fix this issue.

2023-06-13 15:55 UTC, closed without merging